Repository caas-team/new-pykube, pull requests merged in 2024-05, with the labels that each got.

#9 feat: pytest report
  .github/workflows/build-publish-package.yml
  .github/workflows/python-tests.yml
  poetry.lock
  pyproject.toml
Labels: feature

#12 Refactor: Convert README.rst to README.md
  README.md
  README.rst
  pyproject.toml
Labels: documentation, housekeeping

#14 Feat/publish pypi
  .github/workflows/build-publish-package.yml
  README.md
  pyproject.toml
Labels: enhancement, feature

#15 Enhance/update old references
  README.md
  docs/howtos/write-an-operator.rst
  docs/index.rst
  docs/readme.rst
  docs/users.rst
  pykube/config.py
  pykube/http.py
  tests/test_http.py
Labels: enhancement

#20 Bump version to 24.5.2
  pyproject.toml
Labels: enhancement
